# Generated by Django 4.2.3 on 2023-12-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='contact',
            field=models.IntegerField(verbose_name='Contact Number'),
        ),
    ]
